# Generated by Django 3.2.20 on 2023-07-15 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20230715_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='sakusya',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
