# Generated by Django 3.2.20 on 2023-07-20 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='app.category', verbose_name='カテゴリー'),
            preserve_default=False,
        ),
    ]
