# Generated by Django 3.2.20 on 2023-07-22 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20230722_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='relation',
            field=models.ManyToManyField(blank=True, null=True, related_name='_app_post_relation_+', to='app.Post', verbose_name='関連'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(to='app.Tag', verbose_name='タグ'),
        ),
    ]
