# Generated by Django 3.2.20 on 2023-07-22 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20230722_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='app.Tag', verbose_name='タグ'),
        ),
    ]
